version: 2.7.{build}
pull_requests:
  do_not_increment_build_number: true
build_script:
- cmd: Build.cmd Package
test_script:
- cmd: Build.cmd Test
artifacts:
- path: publish\*.nupkg
  name: Nuget Packages